### ISSUE TITLE
superclass mismatch for class Role

### ISSUE THREAD

**Issue by ahmgeek** [AnalyticsMediaGroup/strongbolt#6]
I already have a model `Role` and table`roles` in my application, when I try to run `rails g strongbolt:install` I have this error:
```
→ bundle exec rails g strongbolt:install                                                                                                                                                                ‹ruby-2.1.5@aurora-server›
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
     skipped  Migration create_strongbolt_tables.rb already exists
/home/ahmgeek/workspace/appenza/development/aurora-server/app/models/role.rb:16:in `<top (required)>': superclass mismatch for class Role (TypeError)
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `load'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:456:in `load_file'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:317:in `depend_on'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:233:in `require_dependency'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/engine.rb:471:in `each'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/engine.rb:471:in `block in eager_load!'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/engine.rb:469:in `each'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/engine.rb:469:in `eager_load!'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/strongbolt-0.3.7/lib/generators/strongbolt/install_generator.rb:16:in `copy_initializer'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/generators.rb:157:in `invoke'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

```

**Comment by tobithiel** [comment]
Sorry about that. Strongbolt was breaking out of its namespace for some models. Please try the new version 0.3.8 that I just published. It should fix your problem.
Let me know if that worked for you :)

**Comment by ahmgeek** [comment]
do you know that I love you ? :heart: :blue_heart: :green_heart:
