### ISSUE TITLE
Booting with multiple workers.

### ISSUE THREAD

**Issue by ahmgeek** [AnalyticsMediaGroup/strongbolt#9]
I have some issues booting the app after installing strongbolt, basically I have a `procfile` which contains the following commands: 
```
redis: redis-server
web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
mailer: bundle exec rake RAILS_ENV=$RAILS_ENV resque:work QUEUE=* TERM_CHILD=1
transcoder: bundle exec rake RAILS_ENV=$RAILS_ENV resque:work QUEUE=* TERM_CHILD=1
scheduler: bundle exec rake RAILS_ENV=$RAILS_ENV resque:scheduler QUEUE=* TERM_CHILD=1

```

it fails when it hits the mailer to scheduler
```
20:23:26 web.1        | I, [2016-05-16T20:23:26.734504 #23742]  INFO -- : listening on addr=0.0.0.0:3000 fd=11
20:23:26 web.1        | I, [2016-05-16T20:23:26.740919 #23742]  INFO -- : master process ready
20:23:26 web.1        | I, [2016-05-16T20:23:26.742798 #23764]  INFO -- : worker=0 ready
20:23:26 mailer.1     | rake aborted!
20:23:26 mailer.1     | TypeError: no implicit conversion of nil into String
20:23:26 mailer.1     | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/utils.rb:24:in `quote_ident'
20:23:26 mailer.1     | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/utils.rb:24:in `quoted'
20:23:26 mailer.1     | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/quoting.rb:31:in `quote_table_name'
20:23:26 mailer.1     | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:738:in `column_definitions'
20:23:26 mailer.1     | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
20:23:26 mailer.1     | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
20:23:26 mailer.1     | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/attributes.rb:93:in `columns'
20:23:26 mailer.1     | /home/ahmgeek/workspace/appenza/development/aurora-server/lib/tasks/resque.rake:7:in `block (3 levels) in <top (required)>'
20:23:26 mailer.1     | /home/ahmgeek/workspace/appenza/development/aurora-server/lib/tasks/resque.rake:7:in `each'
20:23:26 mailer.1     | /home/ahmgeek/workspace/appenza/development/aurora-server/lib/tasks/resque.rake:7:in `block (2 levels) in <top (required)>'
20:23:26 mailer.1     | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/bin/ruby_executable_hooks:15:in `eval'
20:23:26 mailer.1     | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/bin/ruby_executable_hooks:15:in `<main>'
20:23:26 mailer.1     | Tasks: TOP => resque:work => resque:preload => resque:setup
20:23:26 mailer.1     | (See full trace by running task with --trace)
20:23:26 mailer.1     | exited with code 1
20:23:26 system       | sending SIGTERM to all processes
20:23:26 redis.1      | 23741:signal-handler (1463423006) Received SIGTERM scheduling shutdown...
20:23:26 web.1        | Unicorn master intercepting TERM and sending myself QUIT instead
20:23:26 scheduler.1  | terminated by SIGTERM
20:23:26 transcoder.1 | terminated by SIGTERM
20:23:26 redis.1      | 23741:M 16 May 20:23:26.968 # User requested shutdown...
20:23:26 redis.1      | 23741:M 16 May 20:23:26.968 * Saving the final RDB snapshot before exiting.
20:23:27              | rake aborted!
20:23:27              | TypeError: no implicit conversion of nil into String
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/utils.rb:24:in `quote_ident'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/utils.rb:24:in `quoted'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/quoting.rb:31:in `quote_table_name'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:738:in `column_definitions'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/attributes.rb:93:in `columns'
20:23:27              | /home/ahmgeek/workspace/appenza/development/aurora-server/lib/tasks/resque.rake:7:in `block (3 levels) in <top (required)>'
20:23:27              | /home/ahmgeek/workspace/appenza/development/aurora-server/lib/tasks/resque.rake:7:in `each'
20:23:27              | /home/ahmgeek/workspace/appenza/development/aurora-server/lib/tasks/resque.rake:7:in `block (2 levels) in <top (required)>'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/bin/ruby_executable_hooks:15:in `eval'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/bin/ruby_executable_hooks:15:in `<main>'
20:23:27              | Tasks: TOP => resque:work => resque:preload => resque:setup
20:23:27              | (See full trace by running task with --trace)
20:23:27 redis.1      | exited with code 0
20:23:27              | 23741:M 16 May 20:23:27.025 * DB saved on disk
20:23:27              | 23741:M 16 May 20:23:27.025 # Redis is now ready to exit, bye bye...
20:23:27              | rake aborted!
20:23:27              | TypeError: no implicit conversion of nil into String
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/utils.rb:24:in `quote_ident'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/utils.rb:24:in `quoted'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/quoting.rb:31:in `quote_table_name'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:738:in `column_definitions'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/activerecord-4.2.1/lib/active_record/attributes.rb:93:in `columns'
20:23:27              | /home/ahmgeek/workspace/appenza/development/aurora-server/lib/tasks/resque.rake:7:in `block (3 levels) in <top (required)>'
20:23:27              | /home/ahmgeek/workspace/appenza/development/aurora-server/lib/tasks/resque.rake:7:in `each'
20:23:27              | /home/ahmgeek/workspace/appenza/development/aurora-server/lib/tasks/resque.rake:7:in `block (2 levels) in <top (required)>'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/gems/resque-scheduler-4.0.0/lib/resque/scheduler/tasks.rb:23:in `block (2 levels) in <top (required)>'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/bin/ruby_executable_hooks:15:in `eval'
20:23:27              | /home/ahmgeek/.rvm/gems/ruby-2.1.5@aurora-server/bin/ruby_executable_hooks:15:in `<main>'
20:23:27              | Tasks: TOP => resque:setup
20:23:27              | (See full trace by running task with --trace)
20:23:27 web.1        | I, [2016-05-16T20:23:27.102226 #23742]  INFO -- : reaped #<Process::Status: pid 23764 exit 0> worker=0
20:23:27 web.1        | I, [2016-05-16T20:23:27.102999 #23742]  INFO -- : master complete
20:23:27 web.1        | exited with code 0
```
I use Foreman to issue the runners.
most of the failures are a rake tasks inside `/lib`
so I don'y know if strongbolt traverse the whole apps and crash in one of those points or what ?

**Comment by tobithiel** [comment]
I don't see anything from Strongbolt in the stack trace, so I don't see how Strongbolt's code would cause this.
Looking at the stack trace, Resque seems to be querying PostgreSQL, which doesn't sound right to me, but shouldn't have anything to do with Strongbolt. I've never used Resque, so maybe that's correct.

But without having source code to look at, I can't really say what's going on. If you can provide a minimal example where it works without Strongbolt and enabling Strongbolt causes the failure, we're happy to look into it.

**Comment by ahmgeek** [comment]
I can provide you a sample of the code, but after a little investigation, I've found the issue, it's related to Unicorn workers, as I said I have Procfile that initiate the workers, supposedly on heroku `Production` when every worker runs, it runs on it's own dyno, like the mailer, scheduler etc..
the problem I see when I start this in my local machine:
```
11:46:10 web.1        | I, [2016-05-17T11:46:10.753296 #10247]  INFO -- : Refreshing Gem list
11:46:14 web.1        | D, [2016-05-17T11:46:14.983595 #10247] DEBUG -- : -------------------------------------------------------------------
11:46:14 web.1        | Configuring tenant Organization
11:46:14 web.1        | -------------------------------------------------------------------
11:46:14 web.1        | 
11:46:14 web.1        | 
11:46:15 web.1        | D, [2016-05-17T11:46:15.137175 #10247] DEBUG -- : -------------------------------------------------------------------
11:46:15 web.1        | Configuring tenant School
11:46:15 web.1        | -------------------------------------------------------------------
11:46:15 web.1        | 
11:46:15 web.1        | 
11:46:15 web.1        | D, [2016-05-17T11:46:15.144086 #10247] DEBUG -- : -------------------------------------------------------------------
11:46:15 web.1        | Configuring tenant Category
11:46:15 web.1        | -------------------------------------------------------------------
11:46:15 web.1        | 
11:46:15 web.1        | 
11:46:15 mailer.1     | D, [2016-05-17T11:46:15.227923 #10249] DEBUG -- : -------------------------------------------------------------------
11:46:15 mailer.1     | Configuring tenant Organization
11:46:15 mailer.1     | -------------------------------------------------------------------
11:46:15 mailer.1     | 
11:46:15 mailer.1     | 
11:46:15 transcoder.1 | D, [2016-05-17T11:46:15.273514 #10251] DEBUG -- : -------------------------------------------------------------------
11:46:15 transcoder.1 | Configuring tenant Organization
11:46:15 transcoder.1 | -------------------------------------------------------------------
11:46:15 transcoder.1 | 
11:46:15 transcoder.1 | 
11:46:15 mailer.1     | D, [2016-05-17T11:46:15.315111 #10249] DEBUG -- : -------------------------------------------------------------------
11:46:15 mailer.1     | Configuring tenant School
11:46:15 mailer.1     | -------------------------------------------------------------------
11:46:15 mailer.1     | 
11:46:15 mailer.1     | 
11:46:15 mailer.1     | D, [2016-05-17T11:46:15.321787 #10249] DEBUG -- : -------------------------------------------------------------------
11:46:15 mailer.1     | Configuring tenant Category
11:46:15 mailer.1     | -------------------------------------------------------------------
11:46:15 mailer.1     | 
11:46:15 mailer.1     | 
11:46:15 scheduler.1  | D, [2016-05-17T11:46:15.331954 #10255] DEBUG -- : -------------------------------------------------------------------
11:46:15 scheduler.1  | Configuring tenant Organization
11:46:15 scheduler.1  | -------------------------------------------------------------------
11:46:15 scheduler.1  | 
11:46:15 scheduler.1  | 
11:46:15 transcoder.1 | D, [2016-05-17T11:46:15.377169 #10251] DEBUG -- : -------------------------------------------------------------------
11:46:15 transcoder.1 | Configuring tenant School
11:46:15 transcoder.1 | -------------------------------------------------------------------
11:46:15 transcoder.1 | 
11:46:15 transcoder.1 | 
11:46:15 transcoder.1 | D, [2016-05-17T11:46:15.389705 #10251] DEBUG -- : -------------------------------------------------------------------
11:46:15 transcoder.1 | Configuring tenant Category
11:46:15 transcoder.1 | -------------------------------------------------------------------
11:46:15 transcoder.1 | 
11:46:15 transcoder.1 | 
11:46:15 scheduler.1  | D, [2016-05-17T11:46:15.429146 #10255] DEBUG -- : -------------------------------------------------------------------
11:46:15 scheduler.1  | Configuring tenant School
11:46:15 scheduler.1  | -------------------------------------------------------------------
11:46:15 scheduler.1  | 
11:46:15 scheduler.1  | 
11:46:15 scheduler.1  | D, [2016-05-17T11:46:15.436636 #10255] DEBUG -- : -------------------------------------------------------------------
11:46:15 scheduler.1  | Configuring tenant Category
11:46:15 scheduler.1  | -------------------------------------------------------------------
11:46:15 scheduler.1  | 
11:46:15 scheduler.1  | 
11:46:16 web.1        | I, [2016-05-17T11:46:16.114786 #10247]  INFO -- : listening on addr=0.0.0.0:3000 fd=11
11:46:16 web.1        | I, [2016-05-17T11:46:16.120810 #10247]  INFO -- : master process ready
11:46:16 web.1        | I, [2016-05-17T11:46:16.122787 #10267]  INFO -- : worker=0 ready
11:46:16 mailer.1     | rake aborted!
11:46:16 mailer.1     | TypeError: no implicit conversion of nil into String
```
as you can see, I have some tenants in `stongbolt` initializer, every time a worker runs it initiate same tenants  every time.
when I remove the workers from the `Procfile` it starts normally, I don't know it that will be a problem on production or no, so you may clarify this a little bet.
Thanks.

**Comment by tobithiel** [comment]
It is expected that each process initializes the tenants independently. Since they're separate Ruby VMs, that has to be done so Strongbolt is accessible in these workers as well.

**Comment by ahmgeek** [comment]
Aaah, I guess I know where the issue come from:
```
require 'resque/tasks'
require 'resque/scheduler/tasks'

# load the Rails app all the time
namespace :resque do
  task setup: :environment do
    ActiveRecord::Base.descendants.each { |klass| klass.columns }
    Resque.before_fork = Proc.new { ActiveRecord::Base.establish_connection }
    Resque.redis = Rails.application.secrets.redis_url
    Resque.redis.namespace = "resque"
  end

  task setup_schedule: :setup do
    require 'resque-scheduler'
  end

  task :scheduler => :setup_schedule
end
```
this rake task is the reason it fails.

**Comment by tobithiel** [comment]
Is this failing on a Strongbolt model? If yes, on which one?
Otherwise I don't think this is a Strongbolt issue.

**Comment by ahmgeek** [comment]
well, let me close the issue for now, until I do more research.
